config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome'

  get 'errors/not_found'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
                                        registrations: 'users/registrations' }

  resources :users, only: [:show]
  resources :categories, only: [:show]

  resources :questions do
    resources :answers
    put :favorite, on: :member
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, 
               use: :slugged 

  has_many :authored_questions, 
            class_name: 'Question', 
            foreign_key: :author_id

  has_many :answers

  has_many :answered_questions, 
            through: :answers, 
            source: :question

  has_many :favorite_questions
  
  has_many :favorites, 
            through: :favorite_questions, 
            source: :question          
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         # :recoverable, 
         :rememberable, 
         :trackable, 
         :validatable,
         :omniauthable, 
         :omniauth_providers => [:facebook]

  validates_presence_of :name

  enum role: [:user, :admin]

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    role.to_i ||= :user
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end      
  end 

  def has_created_any_question?
    authored_questions.present?
  end 

  def has_answered_any_question?
    answers.present?
  end

  def has_favorite_questions?
    favorites.present?
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    if current_user.provider == "facebook"
      params.delete("current_password")
      resource.update_without_password(params)
      resource.save
    else
      resource.update_with_password(params)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_show.html.erb
<% if user.has_created_any_question? %>
    <dd><strong>Questions Asked:</strong></dd></br>
    
    <% user.authored_questions.each do |question| %>
      <dd><%= link_to question.title, question %></dd>
    <% end %></br>
  <% end %>  


  <% if user.has_answered_any_question? %>
    <dd><strong>Answers:</strong></dd></br>

    <% user.answers.each do |answer| %>
      <% if answer.question.present? %>
      <dd><%= link_to truncate(answer.content, length: 50) + "(read more)", question_answer_path(answer.question, answer) %></dd>
      <% end %>
    <% end %> </br>
  <% end %> 

  <% if user.has_favorite_questions? %>
    <dd><strong>Favorited Questions:</strong></dd></br>
    
    <% user.favorites.each do |favorite| %>
        <dd><%= link_to favorite.title, question_path(favorite) %>
        <% if current_user == user %>
          <%= link_to "remove", favorite_question_path(favorite, type: "unfavorite"), method: :put, :class => 'label label-danger' %></dd>
        <% end %>  
    <% end %> 
  <% end %>
  
  <% unless user.has_created_any_question? || user.has_answered_any_question? || user.has_favorite_questions?  %>  
    <p>Hi <%= user.name %>, All your action will be displayed here!</p>
  <% end %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%= @user.name %></h1>
</div>

<dl>
  <%= render 'user_show', user: @user %>
</dl>

<%= link_to "Back", :back, :class => 'btn btn-primary' %> 