config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome'

  get 'errors/not_found'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
                                        registrations: 'users/registrations' }

  resources :users, only: [:show]
  resources :categories, only: [:show]

  resources :questions do
    resources :answers
    put :favorite, on: :member
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    @disable_nav = true
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end
end

app/views/home/_welcome_actions.html.erb
<% if current_user %>
   <%= link_to "Click Here - Ask a Question", new_question_path, class: "btn btn-info log-block  col-md-offset-3 text-center " %>
<% else %>
  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <br />
    <%= link_to "Sign Up To Ask A Question", new_registration_path(resource_name), :class => 'btn btn-info log-block col-md-offset-3 text-center ' %>
  <% end -%> 

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
    <br />
      <%= link_to omniauth_authorize_path(resource_name, provider), :class => 'btn btn-social btn-facebook log-block col-md-offset-3 text-center' do %> 
        <span class="fa fa-facebook"></span>Login With Facebook!
      <% end %>
    <% end -%>
  <% end %> 
<% end %>

app/views/home/welcome.html.erb
<body class="welcome">
  <div class="container fluid full">
    <div class="row">
      <div class="span4"><%= image_tag 'logo.png', :class => "center-block welcome-image" %></div><br />
    </div>
  </div>  
  <div class="col-md-3 col-md-offset-6">
    <%= render 'welcome_actions' %>
  </div>
</body>  