config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome'

  get 'errors/not_found'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
                                        registrations: 'users/registrations' }

  resources :users, only: [:show]
  resources :categories, only: [:show]

  resources :questions do
    resources :answers
    put :favorite, on: :member
  end

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert"></button>
    <%= message %>
  </div>
<% end %>

<script type="text/javascript">
  window.setTimeout(function() 
   {
  $(".alert").fadeTo(500, 0).slideUp(300, function()
  {
  $(this).remove();
  });
  }, 2000);
</script>

app/views/layouts/_footer.html.erb
<div class="container text-center">
  <p class="text">&copy; AskMe! 2016
  <i class="glyphicon glyphicon-heart" style="color:red"></i></p>
  <div class="social">
    <a href="https://www.facebook.com/Phaltoe" target="_blank"><i class="fa fa-facebook" style="color:#3B5998"></i></a>
    <a href="https://github.com/phaltoe/askme" target="_blank"><i class="fa fa-github" style="color:#333333"></i></a>
    <a href="https://twitter.com/phaltoe85" target="_blank"><i class="fa fa-twitter" style="color:#33CCFF"></i></a>
    <a href="https://br.linkedin.com/in/phaltoe" target="_blank"><i class="fa fa-linkedin" style="color:#007bb5"></i></a>  
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="col-lg-3">
  <div class="well sidebar-nav">
    <h3>Trending Questions</h3>
    <ul class="nav nav-list">
      <li class="nav-header nav-fixed"></li>
      <% Question.most_answered.each do |question| %>
        <li><%= link_to question.title, question_path(question) %></li>
      <% end %>  
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AskMe" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top bg-faded">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" <%= link_to image_tag('logo.png'), root_path, id: "logo" %></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Questions', questions_path%></li>
            <%= render 'devise/menu/registration_items' %>
            <%= render 'devise/menu/login_items' %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= render partial: "layouts/flash_messages", flash: flash %>
          <%= yield %>
        </div>
         <%= render 'layouts/sidebar' unless @disable_nav %> 
      </div><!--/row-->
      <div id="footer">
        <%= render 'layouts/footer' %>
      </div>
    </div> <!-- /container -->
  </body>
</html>